### ISSUE TITLE
Right legend button error

### ISSUE THREAD

**Issue by bchartier** [Ville-Eurometropole-Strasbourg/image_compare#1]
I get the following error when I click on the legend button for the right hand side layer :
```
IHM.js:271 Uncaught ReferenceError: langue is not defined
    at HTMLImageElement.<anonymous> (IHM.js:271:56)
    at HTMLImageElement.dispatch (jquery-3.2.1.min.js:3:10316)
    at q.handle (jquery-3.2.1.min.js:3:8343)
```

This seems to be due to a typo in the following line:
https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/IHM.js#L271

I think you should replace
`titre_couche_WMS= FS.main.donnees[i][5+langue];`
by
`titre_couche_WMS= FS.main.donnees[i][5+FS.main.langue];`

similarly to 
https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/IHM.js#L254

**Comment by GCT-EMS** [comment]
You are right. This is fixed by the last merge of your pull request with your corrections.
