### ISSUE TITLE
Ajouter certaines valeurs dans un fichier JSON ou JS de configuration

### ISSUE THREAD

**Issue by gryckelynck** [Ville-Eurometropole-Strasbourg/image_compare#3]
Il pourrait être intéressant de placer certaines valeurs dans un fichier JSON ou JS de configuration de façon à centraliser le paramétrage de l'application.
Par exemple, les valeurs d'emprise et de zoom par défaut de la carte: cf. https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/main.js#L142-L144 et https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/main.js#L142-L144
De même certaines valeurs dans Fonction.js: cf. https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/Fonction.js#L117-L121 (utiliser éventellement le fichier de traduction?)

**Comment by GCT-EMS** [comment]
En effet, un premier fichier JSON permet de configurer plutôt les aspects liés aux données (donnees.json) mais les autres paramétrages de l'application sont dispersés dans le code.

Il serait pertinent de regrouper :
- les couleurs de l'application (début du fichier main.js)
- centre de vue, étendue, zoom min, zoom max (comme indiqué dans la demande)
- la plateforme d'hébergement des données (comme indiqué dans la demande)
- le système de coordonnées des mesures cf.[https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/Fonction.js#L345-L385]
- API de recherche d'adresse cf. [https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/js/Fonction.js#L1029]

**Comment by GCT-EMS** [comment]
Pris en compte dans la version 1.5
