### ISSUE TITLE
Remplacer le numéro d'ordre des couches par leur nom dans les permanliens

### ISSUE THREAD

**Issue by gryckelynck** [Ville-Eurometropole-Strasbourg/image_compare#4]
Acuellement dans les permaliens, les couches sont référencées par leur numéro d'ordre (ex.: `I1=5&I2=7`).
Si on change l'ordre des couches ou on ajoute/supprime des couches intermédiaires dans la liste (cf. https://github.com/Ville-Eurometropole-Strasbourg/image_compare/blob/master/donnees.json), alors les permaliens ne sont plus valident (les couches désignées ne sont plus les bonnes).
Il pourrait donc être intéressant d'utiliser le "internal name" comme référence dans l'URL à la place.

**Comment by GCT-EMS** [comment]
En effet, "internal_name" est suffisamment compact pour être utilisé dans une URL sous réserve de respecter quelques règles de nommage (pas d'accent, pas d'espace, etc.).

A programmer dans la prochaine version...

**Comment by GCT-EMS** [comment]
Pris en compte dans la version 1.5
